#+TITLE: rcirc-styles.el

[[http://melpa.org/#/rcirc-styles][http://melpa.org/packages/rcirc-styles-badge.svg]]
[[http://stable.melpa.org/#/rcirc-styles][http://stable.melpa.org/packages/rcirc-styles-badge.svg]]
[[https://travis-ci.org/aaron-em/rcirc-styles.el.svg][https://travis-ci.org/aaron-em/rcirc-styles.el.svg]]

Giving rcirc correct and complete support for mIRC-style color and
attribute codes

Copyright © 2015 Aaron Miller. All rights reversed. Share and Enjoy!

Last revision: Sunday, December 20, 2015, ca. 14:00.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with this program; if not, write to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
MA 02111-1307 USA

** Commentary

The de facto standard for IRC color codes, as originally
implemented in mIRC, can be found at
http://en.wikichip.org/wiki/irc/colors.

As may be expected from the context, it's a bit ad hoc and not the
easiest thing in the world to parse correctly, which may explain why a
prior attempt to satisfy this use case, under the name of
"rcirc-controls.el", attempted to do so with a recondite yet woefully
inadequate regexp.

Rather than attempt to fix the regexp, and even if successful make
it even more incomprehensible than it started out being, I decided
it'd be easier and more maintainable to write a string-walking
parser.

So I did that. In addition to those cases supported in the previous
library, this code correctly handles:
- Background colors, including implicit backgrounds when a new code
  provides only a foreground color.
- Colors at codes between 8 and 15 (and correct colors for codes < 8).
- Color specifications implicitly terminated by EOL.
- Color specifications implicitly terminated by new color
  specifications.
- The =^O= character terminating color specifications.

While I was at it, I noticed some areas in which the both the stock
attribute markup function in rcirc, and the one provided in the
previous library, could use improving.

So I did that too, and the following cases are now correctly handled:
- Implicit termination of attribute markup by EOL.
- =^V= as the specifier for reverse video, rather than italics.
- =^]= as the specifier for italics.

As far as I'm aware, this code implements correct and complete
support for mIRC colors and attributes. If I've missed something,
let me know!
